/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hw9 */

#ifndef _Included_hw9
#define _Included_hw9
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hw9
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_hw9_func
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
